export const unites = [
    {
        id: "0",
        title: "Aire",
        types: [
                    "Acres (ac)", 
                    "Ares (a)", 
                    "Hectares (ha)", 
                    "Centimètres carrés (cm²)",
                    "Pieds carrés (ft²)",
                    "Pouces carrés (in²)",
                    "Mètres carrés (m²)",
                ],
    },
    {
        id: "1",
        title: "Longueur",
        types: [
                    "Millimètres (mm)",
                    "Centimètres (cm)",
                    "Mètres (m)",
                    "Kilomètres (km)",
                    "Pouces (in)",
                    "Pieds (ft)",
                    "Yards (yd)",
                    "Miles (mi)",
                    "Milles nautique (NM)",
                    "Mils (mil)",
                ],
    },
    {
        id: "2",
        title: "Température",
        types: [
                    "Celsius (°C)",
                    "Fahrenheit (°F)",
                    "Kelvin (K)",
               ],
    },
    {
        id: "3",
        title: "Volume",
        types: [
                    "Gallons britanniques (gal)",
                    "Gallons américains (gal)",
                    "Litres (l)",
                    "Millilitres (ml)",
                    "Centimètres cubes (cc) (cm³)",
                    "Mètres cubes (m³)",
                    "Pouces cubes (in³)",
                    "Pieds cubes (ft³)",
                ],
    },
    {
        id: "4",
        title: "Masse",
        types: [
                    "Tonnes (t)",
                    "Tonnes britanniques (t)",
                    "Tonnes américaines (t)",
                    "Livres (lb)",
                    "Onces (oz)",
                    "Kilogrammes (kg)",
                    "Grammes (g)",
                ],
    },
    {
        id: "5",
        title: "Données",
        types: [
                    "Bits (bit)",
                    "Octets (o)",
                    "Kilooctets (Ko)",
                    "Kibioctets (KiB)",
                    "Mégaoctets (Mo)",
                    "Mébioctets (MiB)",
                    "Gigaoctets (Go)",
                    "Gibioctets (GiB)",
                    "Téraoctets (To)",
                    "Tébioctets (TiB)",
                ],
    },
    {
        id: "6",
        title: "Vitesse",
        types: [
                    "Mètres par seconde (m/s)",
                    "Mètres par heure (m/h)",
                    "Kilomètres par seconde (km/s)",
                    "Kilomètres par heure (km/h)",
                    "Pouces par seconde (in/s)",
                    "Pouces par heure (in/h)",
                    "Pieds par seconde (ft/s)",
                    "Pieds par heure (ft/h)",
                    "Miles par seconde (mi/s)",
                    "Miles par heure (mi/h)",
                    "Noeuds (kn)",
                ],
    },
    {
        id: "7",
        title: "Temps",
        types: [
                    "Millisecondes (ms)",
                    "Secondes (s)",
                    "Minutes (min)",
                    "Heures (h)",
                    "Jours (d)",
                    "Semaines (wk)",
                ],
    },
];